# Generated by Django 2.0.1 on 2018-01-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20180107_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
