# Generated by Django 2.0.1 on 2018-01-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_auto_20180107_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
