# Generated by Django 2.0.1 on 2018-01-13 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='kiosk.Product'),
        ),
    ]
