# Generated by Django 2.0.1 on 2018-01-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosk', '0007_auto_20180113_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('is_actual', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='check_time',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.AddField(
            model_name='sale',
            name='count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kiosk.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Provider'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(to='kiosk.Ingredient'),
        ),
        migrations.AddField(
            model_name='sale',
            name='fiscal_check',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kiosk.FiscalCheck'),
            preserve_default=False,
        ),
    ]
