# Generated by Django 2.0.1 on 2018-01-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_auto_20180113_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0)),
                ('is_actual', models.BooleanField(default=True)),
                ('consumables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Consumables')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Provider')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='is_actual',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kiosk.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='consumables',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kiosk.Consumables'),
            preserve_default=False,
        ),
    ]
