# Generated by Django 2.0.1 on 2018-01-23 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosk', '0009_auto_20180113_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalcheck',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='consumables',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='provider',
        ),
        migrations.RenameField(
            model_name='consumables',
            old_name='size',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='count',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='fiscal_check',
        ),
        migrations.AddField(
            model_name='sale',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FiscalCheck',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
