# Generated by Django 2.0.1 on 2018-02-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0010_auto_20180123_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='quantity_of_pack',
            field=models.FloatField(default=0),
        ),
    ]
