# Generated by Django 2.0.1 on 2018-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0011_consumables_quantity_of_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, default='images/', upload_to='', verbose_name="Product's icon"),
        ),
    ]
