# Generated by Django 2.0.1 on 2018-02-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0012_product_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(upload_to='images/', verbose_name="Product's icon"),
        ),
    ]
