# Generated by Django 2.0.1 on 2018-02-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0014_auto_20180208_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(upload_to='static/img/', verbose_name="Product's icon"),
        ),
    ]
