# Generated by Django 2.0.1 on 2018-02-09 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiosk', '0015_auto_20180208_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='check_time',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.AddField(
            model_name='sale',
            name='check_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kiosk.CheckList'),
            preserve_default=False,
        ),
    ]
