# Generated by Django 2.0.1 on 2018-02-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0016_auto_20180209_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='check_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.CheckList'),
        ),
    ]
