# Generated by Django 2.0.1 on 2018-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0017_auto_20180209_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
