# Generated by Django 2.0.1 on 2018-03-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0018_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumables',
            old_name='quantity_of_pack',
            new_name='volume',
        ),
    ]
